import { fabric } from 'fabric';
export const propertiesToInclude = [
  'id',
  'name',
  'locked',
  'file',
  'src',
  'link',
  'tooltip',
  'animation',
  'layout',
  'workareaWidth',
  'workareaHeight',
  'videoLoadType',
  'autoplay',
  'shadow',
  'muted',
  'loop',
  'code',
  'icon',
  'userProperty',
  'trigger',
  'configuration',
  'superType',
  'points',
  'svg',
  'loadType',
];

export const defaultOption = {
  fill: '#f0f0f0',
  stroke: '#8c8c8c',
  strokeUniform: true,
  resource: {},
  link: {
    enabled: false,
    type: 'resource',
    state: 'new',
    dashboard: {},
  },
  tooltip: {
    enabled: true,
    type: 'resource',
    template: '<div>{{message.name}}</div>',
  },
  animation: {
    type: 'none',
    loop: true,
    autoplay: true,
    duration: 1000,
  },
  backgroundColor: '#fff',
  userProperty: {},
  trigger: {
    enabled: false,
    type: 'alarm',
    script: 'return message.value > 0;',
    effect: 'style',
  },
};
export const initValues = {
  selectedItem: null,
  zoomRatio: 1,
  preview: false,
  loading: false,
  progress: 0,
  animations: [],
  styles: [],
  dataSources: [],
  editing: false,
  descriptors: {},
  objects: undefined,
};

export const group = (obj: any) => ({
  id: '',
  name: 'New group',
  type: 'group',
  objects: [...obj],
});

export const rect1 = {
  id: '',
  name: 'New shape',
  type: 'rect',
  // type: 'labeledRect',
  // label: 'test',
  stroke: '#7A97CC',
  strokeWidth: 1,
  fill: '#E3F1FF',
  // fill: '#a123cb',
  height: 80,
  width: 80,
  lockUniScaling: true,
};

export const rect = {
  id: '',
  type: 'labeledRect',
  rectOptions: {
    left: 0,
    top: 0,
    width: 200,
    height: 100,
    fill: '#E3F1FF',
    stroke: '#7A97CC',
    strokeWidth: 1,
  },
  textOptions: {
    left: 0,
    top: 0,
    width: 150,
    fill: '#333',
    shadow: new fabric.Shadow({
      color: 'rgba(34, 34, 100, 0.4)',
      blur: 2,
      offsetX: -2,
      offsetY: 2,
    }),
    fontSize: 20,
  },
  text: '鸿星尔克',
};

export const text = {
  id: '',
  text: '绑定新店',
  type: 'i-text',
  fill: '#333',
  // stroke: '#fff',
  strokeWidth: 0.01,
  backgroundColor: 'rgba(255,255,255,.001)',
  textBackgroundColor: 'rgba(255,255,255,.2)',
  fontSize: 16,
  originX: 'center',
  originY: 'center',
  hasControls: false,
  isEditing: false,
  lockScalingX: false,
  lockScalingY: false,
  editable: false,
  fixedFontSize: 16,
  lockUniScaling: false,
  evented: false,
  // shadow: '4px 3px 5px #b2b7bf',
  // textShadow: '4px 3px 5px #b2b7bf',
};

export const circle = {
  id: '',
  name: 'New shape',
  radius: 60,
  type: 'circle',
  stroke: '#7A97CC',
  strokeWidth: 1,
  fill: '#E3F1FF',
  backgroundColor: 'rgba(255,255,255,.1)',
};
