export const propertiesToInclude = [
  'id',
  'name',
  'locked',
  'file',
  'src',
  'link',
  'tooltip',
  'animation',
  'layout',
  'workareaWidth',
  'workareaHeight',
  'videoLoadType',
  'autoplay',
  'shadow',
  'muted',
  'loop',
  'code',
  'icon',
  'userProperty',
  'trigger',
  'configuration',
  'superType',
  'points',
  'svg',
  'loadType',
];

export const defaultOption = {
  fill: '#f0f0f0',
  stroke: '#8c8c8c',
  strokeUniform: true,
  resource: {},
  link: {
    enabled: false,
    type: 'resource',
    state: 'new',
    dashboard: {},
  },
  tooltip: {
    enabled: true,
    type: 'resource',
    template: '<div>{{message.name}}</div>',
  },
  animation: {
    type: 'none',
    loop: true,
    autoplay: true,
    duration: 1000,
  },
  backgroundColor: '#fff',
  userProperty: {},
  trigger: {
    enabled: false,
    type: 'alarm',
    script: 'return message.value > 0;',
    effect: 'style',
  },
};
export const initValues = {
  selectedItem: null,
  zoomRatio: 1,
  preview: false,
  loading: false,
  progress: 0,
  animations: [],
  styles: [],
  dataSources: [],
  editing: false,
  descriptors: {},
  objects: undefined,
};

export const group = (obj: any) => ({
  id: '',
  name: 'New group',
  type: 'group',
  objects: [...obj],
});

export const rect = {
  id: '',
  name: '矩形',
  type: 'labeledRect',
  // text: '武松',
  stroke: '#7A97CC',
  strokeWidth: 1,
  fill: '#E3F1FF',
  height: 200,
  width: 100,
  visible: true,
  locked: false,
  lockUniScaling: true,
  opacity: 0.7,
};

export const circle = {
  id: '',
  name: '圆形',
  type: 'LabeledCircle',
  // text: '武松1',
  radius: 60,
  stroke: '#7A97CC',
  strokeWidth: 1,
  fill: '#E3F1FF',
  visible: true,
  locked: false,
  backgroundColor: 'rgba(255,255,255,.1)',
  opacity: 0.7,
};

export const text = {
  id: '',
  text: '绑定新店',
  type: 'i-text',
  fill: '#333',
  strokeWidth: 0.01,
  backgroundColor: 'rgba(255,255,255,.001)',
  textBackgroundColor: 'rgba(255,255,255,.2)',
  fontSize: 14,
  // shadow: 'rgba(0,0,0,0.2) 0 0 5px',
  fontStyle: 'normal',
  fontFamily: 'sans-serif',
  evented: true,
  originX: 'center',
  originY: 'center',
  textAlign: 'center',
  // shadow: '4px 3px 5px #b2b7bf',
  // textShadow: '4px 3px 5px #b2b7bf',
};

export const bg = {
  id: '',
  type: 'BgImage',
  name: '背景底图',
  src: '',
  width: 500,
  height: 500,
  scaleX: 0.2,
  scaleY: 0.2,
};

export const marker = {
  id: '',
  type: 'i-text',
  name: '标记',
  src: '',
  fontSize: 60,
  width: 30,
  height: 30,
  visible: true,
  locked: false,
};
